apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-checkin-app
  namespace: flight-reservation
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: flight-checkin-app
  template:
    metadata:
      labels:
        app: flight-checkin-app
    spec:
      containers:
        - name: flight-checkin-app
          image: anuragpatilcloud/flight-checkin-app:8
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mariadb:3306/checkin_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flight-reservation-secrets
                  key: DB_ROOT_PASSWORD
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.MariaDBDialect"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_AUTO_QUOTE_KEYWORD
              value: "true"
            - name: BOOKING_SERVICE_URL
              value: "http://flight-reservation-service:8080/api/bookings"
            - name: FRONTEND_URL
              value: "http://flight-frontend"
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
