apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flight-reservation
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_GITHUB_USER/flight-reservation-multicloud.git
    targetRevision: main
    path: aws/gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: flight-reservation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
