apiVersion: v1
kind: Service
metadata:
  name: flight-checkin-service
  namespace: flight-reservation
spec:
  type: ClusterIP
  selector:
    app: flight-checkin-app
  ports:
    - port: 8081
      targetPort: 8081
      name: http
