apiVersion: v1
kind: Service
metadata:
  name: flight-frontend
  namespace: flight-reservation
spec:
  type: LoadBalancer
  selector:
    app: flight-frontend
  ports:
    - port: 80
      targetPort: 80
      name: http
